CREATE TABLE movie (
	id CHAR(8) PRIMARY KEY,
	name VARCHAR(128),
	year INTEGER, rating VARCHAR(5) DEFAULT NULL,
	runtime INTEGER, genre VARCHAR(16),
	earnings_rank INTEGER DEFAULT NULL);

CREATE TABLE person(
	id CHAR(8) PRIMARY KEY,
	name VARCHAR(128),
	born INTEGER DEFAULT NULL,
	pob VARCHAR(128) DEFAULT NULL);

CREATE TABLE director (
	director_id CHAR(8),
	movie_id CHAR(8),
	PRIMARY KEY CLUSTERED(director_id ASC, movie_id ASC),
	FOREIGN KEY(director_id) REFERENCES person(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	FOREIGN KEY(movie_id) REFERENCES movie(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);

CREATE TABLE actor (
	actor_id CHAR(8),
	movie_id CHAR(8),
	PRIMARY KEY CLUSTERED(actor_id ASC, movie_id ASC),
	FOREIGN KEY(actor_id) REFERENCES person(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	FOREIGN KEY(movie_id) REFERENCES movie(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);

CREATE TABLE oscar (
	movie_id CHAR(8) NOT NULL,
	person_id CHAR(8) DEFAULT NULL,
	type VARCHAR(23) NOT NULL,
	year INTEGER NOT NULL,
	FOREIGN KEY(movie_id) REFERENCES movie(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	FOREIGN KEY(person_id) REFERENCES person(id)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);
